# Вовед {#intro}

Овој текст е обид да се направи преглед и понудат препораки за безбедна пракса при ракување, анализирање, и објавување на податоци. Под „безбедна пракса“ подразбираме чекори кои доколку ги следиме ќе имаме некоја сигурност дека резултатот кој ние го презентираме може било кој да го добие доколку ги користи истите податоци и следи истите процедури кои ги објавуваме заедно со резултатот.

Се чини дека оваа поента е доволно очигледна да некој би рекол дека и воопшто нема потреба да се зборува за ова. Сите се согласуваме со тоа дека кога нашата колешка ќе направи некаква анализа, ние, доколку имаме доволно информации за нејзината анализа, можеме да ја повториме и да ги добиреме _истите_ резултати. Но во пракса оваа удобна идеја ретко кога се остварува. Наместо репродуцибилност, кога се обидуваме да повториме некоја анализа, вообичаено е да се соочиме со забуна и фрустрација. Ова често завршува со откажување или правење на анализата од почеток, односно, безполезно и контрапродуктивно губење на време, ресурси, пари, итн.

Самата дефиниција на „безбедна пракса“ (без преправање дека ова е некаква прецизна дефиниција) повикува барем две дополнителни поенти за тоа што подразбира да анализираме податоци и објавувиме резултати на начин што овозможува точно повторување. Имено, објавувањето на резултат мора да биде поддржано со објавување на 1) точните податоци кои биле употребени да се направи анализата, и 2) деталната процедура која била извршена за да се добие резултатот. Подоцна ќе видиме зошто се неопходни овие компоненти (иако веруваме дека е горе-доле очигледно) и на кој начин е најдобро да се презентираат/објават.

## Организација 

Темата на овој текст е доволно опширна да тука нема ни да се обидеме да дадеме севкупен третмант на сите значајни аспекти. Туку, целта е да дадеме краток преглед на главните принципи за повторливи анализи и практични примери за главните препораки.

По воведот, прво ќе се запознаеме со софтверските алатки кои ќе ги користиме понатаму (Поглавје 2: Алатки), и ќе посочиме некои од најчестите случаи кога една анализа, дури и да имаме најдобри намери, може да биде “неповторлива“ (Поглавје 3: Чести проблеми и ... ???). Понатаму ќе ги разгледаме главните начини на кои постоечки, нерепродуцибилен код за некоја анализа може да се конвертира во репродуцибилна анализа (Поглавје 4: Брза конверзија во репродуцибилна анализа: Скрипта) и за пишување на документи кои ги покажуваат нашето размислување, претпоставки, хипотези, заедно со кодот што го користиме за нивно тестирање и резултатите од тие тестови (Поглавје 5: Репродуцибилни документи / извештаи (Rmd)). За крај, ќе зборуваме за контола на изворниот код со `git` што ни дава слобода и безбедност за променување и подобрување (Поглавје 6: Контрола на изворниот код (git / GitHub)) и за случаевите кога дури и се околу нашата анализа да е репродуцибилно, некој едноставно не може да ја повтори нашата анализа бидејќи нема пристап до алатките кои ние го користиме (Поглавке 7: Што ако вашиот колега има Mac, или друга верзија на `R`? Docker.). Текстот го затвораме со заклучок и литература со препорака да во најмала рака ги погледнете ресурсите дадени во библиографијата бидејќи сорджат далеку подетални и ефективни третмани на темата на репродуцибилно ракување, анализирање и онјавување на податоци.
