# Алатки {#tools}

## Програмски јазик: `R` 

Генерално гледано, во денешно време, доколку анализирате податоци тоа вероратно го правите со помош на `Python` (и пакети како: `pandas, numpy, matplotlib`) или `Р` (со пакети како: `dplyr, data.table, ggplot2`). Доколку работите на пониско ниво или вашата работа е поблиска до математика, можеби користите `c#` за забрзување на вашиот код, но генерално, ретко кога јазик од типот на `c#` сe користи за интерактивна анализа на податоци, графирање, или машинско учење. Конечно понови јазици, како `Julia` и `Scala` имаат дополнителни предности со тоа што овозможуваат полесно пишување код во експлоративни сесии како `Python` ili `R` но со брзина на компутација што е поблиска до `c` или `c#`. Во секој случај, препораките дадени во овој текст се апликабилни без разлика на програмскиот јазик што го користите. 

Во овој текст генерално ќе работиме со софтверски алатки од `R` екосистемот. `R` е програмски јазик пред се наменет кон статистички анализи, и иако не е најраспространет или најшироко користен, е од особено значење за анализа на податоци, и следствено репродуцибилна анализа на податоци. Главните причини за употребата на `R` се дека авторите на овој текст секојдневно користат `R` и `Rstudio` и поради тоа што има еден куп дополнителни екстензии во оваа средина кои овозможуваат лесно пишување технички извештаи, научни трудови (`Rmarkdown`), книги (`bookdown`), веб апликации (`shiny`), блогови (`blogdown`), итн. Самиот овој текст го пишувамe со помош на `bookdown`, што овозможува неверојатно лесно составање и објавивање на подолги текстови (книги) со поглавја, компјутерски код, и математичка нотација со едно копче во `Rstudio`.

Во овој текст немаме намера да навлегуваме длабоко во самото кодирање во `R`. Нашиот приод ќе биде да објасниме одреден принцип со обични зборови и да покажеме како тоа би можело да изгледа со `R` код. Што значи дури и да не знаете ништо за `R` би можеле да го следите текстот и употребите препораките во вашиот омилен програмски јазик за обработка на податоци. 

Во некој делови ќе користиме материјали кои се специфични за `R` и `Rstudio` (на пример `Rmarkdown`) така да можеби ќе има технички детали кои нема да може да директно да ги примените во `Jypiter` тетратка или доколку работите во друг текст едитор (`VScode`). Но повторно, имајќи во предвид дека препораките ќе тежнеат кон тоа како да пишуваме код кој ќе бара минимална интервенција при (ре)анализа на податоци, ваквите аспекти специфични за `Rstudio` ќе бидат сведени на минимум. Генерално, целта ни е да креираме пакет (фолдер) за правење пита што вклучува се што е неопходно за да нашиот пријател може без многу мислење да ја направи истата пита. За да го олесниме овој процес, треба да се стремиме кон тоа да не користиме специјален тарун (софтвер) за да ги сукаме корите, бидејќи таков тарун можеби нема да биде лесно достапен за нашиот пријател. Со други зборови, повторувањето на нашите резултати генерално не треба да зависи од едиторот за текст кој ние го користиме.

## Контрола на изворен код: `git` 

Контрола на изворниот код, најчесто со `git`  (поглавје \@ref(git)), е платформата што ни дава безбедност и слобода во секоја активност поврзана со програмски код, вклучително и при анализирање и ревизирање анализи на податоци. Во основа, `git` e систем за `undo`/`redo` на стероиди, што може да следи две или повеќе верзии на изворниот код (гранки), од два или повеќе компјутери, овозможува соработници од различни локации истовремено да праваt поправки и унапредувања без да си ги пребришуваат промените, и дозволува да се вратите на верзијата од пред два месеци без да ги изгубите меѓувремени промени. Во денешно време е невозможно да се замисли организација која зависи од програмски код за дел од своите фунцкии без употреба на `git` (или друг систем на контрола на изворен код). Стриктно гледано, `git` не е неопходен за правење репродуцибилни анализи. Можно е да напишеме и споделиме скрипта која обработува некои податоците без да ги следиме промените на тој код. Но имајќи во предвид дека при обработка на податоци постојано се соочуваме со одлуки и ревизии, веројатно е ќе се најдеме на брег на река каде што ќе сакаме целиот товар да го спакуваме во водоотпорена вреќа пред да ја преминеме реката. `git` го овозможува токму тоа и скоро сигурно ќе го користите доколку работите на транспарентната анализа на податоци. 

## Виртуелни контејнери: `docker`

Иако досега зборувавме дека, во принцип, репродуцибилните анализи се полесни доколку зависат од помалку алатки и не зависат од работната маса, оваа цел може да стане тешко остварлива, особено имајќи во предвид големите количина на различни типови на податоци (big data) кои се користат во анализи или за предикција. Оттука треба да се запознаеме и со начини на кои можеме да ги пратиме не само нашите состојки (брашно, квасец), рецепта (напишани чекори, слики), и алатки (сукало, тарун) туку и самата соба во која ја правиме питата вклучително и дрвата што ја загреваат фурната како и самата фурна. За споделување од ваков тип ќе зборуваме за `docker` (поглавје \@ref(docker)). `docker` е софтвер за креирање на виртуелен контејнер (пакет) кој покрај програмскиот код (`R` скрипти) и алатките (неопходни `R` пакети) може да вклучува и неопходна верзија на `Rstudio` и надворешни податоци. Ваков приод ни е потребен кога соработниците кои ќе сакаат да ја повторат нашата анализа користат друг оперативен систем, или не се активни корисници на `R` па ги немаат најновите верзии на зависностите, или едноставно кога сакаме да правиме што е можно помалку претпоставки за условите во кои нашата анализа ќе треба да биде повторена.

## Резиме

Корисно е да ги табулираме овие алатки во споредба со компонентите кои ги воведовме претходно во поглавје \@ref(analogy)):

```{r, echo=FALSE, tidy=FALSE}
analogy <- c("Состојки", "Рецепта", "Алатки", "")
component <- c("Податоци", "Изворен код", "Зависности на кодот", "Виртуелен контејнер")
tool <- c("csv, MySQL", "R, git", "dplyr, ggplot2", "docker")

df <- data.frame(analogy, component, tool)
names(df) <- c("Аналог", "Компонента", "Алатка")

knitr::kable(df, caption = "Компонентите на повторување на анализа со соодветните софтверски алатки.")
```
