# Контрола на изворниот код со git и GitHub {#git}

Во другите поглавја генерално зборуваме за R и разни додатни пакети кои се директно поврзани со повторливи анализи. Овие се алатки се во преден план бидејќи се користат за анализа на податоците или поставување на проекти, но самото развивање на еден истражувачки проект, од идеја до публикација, не е прав, асфалтиран, и осветлен пат. Наспроти, секоја скрипта поминува низ неколку верзии пред конечната (`Figure3.2-final-for-print.R`), секој извештај започнува како нацрт кој се ревизира од авторот и неколку соработници, многу табели со податоци са ре-форматираат од почеток или заменуваат. Доколку сте работеле на анализа на податоци, и особено ако тоа го правите со соработници, веројатно ви е позната следната ситуација:

```
sumiraj_trocosi.R
sumiraj_trosoci_po_vraboten.R
sumiraj_trosoci_po_vraboten-2.R
sumiraj_trosoci_final.R
sumiraj_trosoci_juni2020-novo.R
sumiraj_trosoci_juni2020-novo-update.R
...
```

Веројатно не треба да образложуваме зошто ваквата пролиферација на датотеки е проблематична за вашите анализи, па дури и ако не се стремите кон повторливост. Само замислете како изгледа овој директориум кај некој од вашите колеги кој од една страна има сопствени верзии, а од друга страна нема некои од вашите верзии на истата скрипта. Очигледно е дека можеме и мораме да управуваме со изворниот код далеку подобро. Во ова поглавје ќе се запознаеме со некои од начините со кои [`git`](https://git-scm.com/) и [`Github`](https://github.com/) ни помагаат да одржуваме работната средина уредена, да соработуваме и експериментираме безгрижно, и да објавуваме ефективно.

## Основи на `git`

Како што напоменавме претходно, `git` е систем за следење на промените во еден проект, нешто налик на вообичаното `track changes` во `MS Word`, но далеку пософистицирано. Учењето на `git` си бара некое време и трпение, но основите се доволно едноставни да можете веднаш да почнете да користие `git`. Како и во остатокот од текстот, нашата цел во ова поглавје не е да детален осврт на можностите и особеносите на `git` (за тоа видете [тука](https://git-scm.com/book/en/v2)), туку да покажеме како `git` се вклопува во еден повторлив проект и да ве охрабриме до почнете да го користите иако можеби делува комплицирано и застрашувачки.

Еден од најчестите случаи кога ни треба контрола на изворниот код е кога сме стигнале до некоја состојба која фунцкионира или е ставена во употреба (на пример прва верзија од извештајот) и треба да тестираме сугестии од нашите колеги за додавање на нова табела или за поинаков график. Во оваа ситуација, инстинктот кај 99% од нас е да зачуваме копија од оригиналниот извештај кој не сакаме да го изгубиме (можеби во `backup-izvestaj`) и да ги тестираме предлозите за подобрување во „работна“ верзија на извештајот. Иако во овој момент овој план звучи горе-доле безболно, во пракса скоро никогаш не е така Наспроти, нашиот уреден директориум со `mojizvestaj.Rmd` набрзо ќе се претвори во една гужва на датотеки во која што никој, па дури ни ние самите, нема да може да се снајде по неколку недели. 

Со `git` можеме да ја извршиме истата задача но комплетно да ја избегнеме гужвата од датотеки. Задачата „зачувај го оригиналот и чепкај во работна верзија“, концептуално може да се прикаже како едно главно стебло (за оригиналниот извештај кој е веќе во употреба) и една гранка која постои паралелно со главното стебло и во која ние ќе ги тестираме предложените промени.

Контрола на изворниот код (или дури и на целата содржина во еден истражувачки проект) е можна со помош на користење на алатки како [`git`](https://git-scm.com/). Употребата на `Git` е олесната благодарение на веб страниците како што се [`Bitbucket`](https://bitbucket.org/product/), [`Github`](https://github.com/) или [`Gitlab`](https://about.gitlab.com/).

Контролата на содржината е корисна. Кога пишувате текст или код и потоа менувате, `git` овозможува да ги видите тие промени, да споредите, или да ги вратите назад. Може да се каже дека тој е многу напредна верзија на вообичаното `track changes` што се користи во алатки како `MS Word`.

Но, детален осврт на можностите и особеносите на `git` не е тема овде. За тие што се заинтересирани и сакаат да истражуваат постојат ресурси кои детално ги објаснуваат сите детали. На пример: [https://git-scm.com/book/en/v2](https://git-scm.com/book/en/v2).

Овде ќе се осврнеме само на една можност која што ја нуди `Github` за презентирање на `HMTL` документи кои може да произлезат од некои анализи, како на пример со повторливи извештаи во `Rmarkdown`, кои ги конвертираме во `HTML` (поглавје \@ref(proekti)).

`git` функционира со `branches` (гранки). Можете да ги замислите гранките слично како посебни директориуми на вашиот компјутер. Главната гранка (`main`) е местото каде што ги чувате кодот, анализите и податоците. Може да имате многу дополнителни гранки за разни тестови, екпесрименти, верзии, итн. Нешто као кога имате `izvestaj-posledna-verzija-final-za-prin-2.doc`. :) 

Една од гранките кои што се достапни на `Github` има специјално значење и функција. Таа автоматски се објавува на интернет доколку се исполнети неколку услови. Тоа е `gh-pages`. 

`gh-pages` практично овозможува вашиот проект да биде веднаш објавен доколку го имате во `HTML` фомрат. Ако памтите од поглавјето за `Rmarkdown` (поглавје \@ref(rmd)), таквите документи може да се рендерираат во `HTML`. Дополнително олеснување од `Github` е што за `gh-pages` има посебен исклучок и не е потребне посебна гранка. Најлесно од таму содржината се објавува доколку е ставена во папка `docs`.

### Потребен софтвер

За да можете да користите `git` со `rstudio` потребно е да инсталирате `git` од [https://git-scm.com/download/win](https://git-scm.com/download/win). Исто така потребно е да направите ваша сметка на [github.com](https://github.com).

### Поставување 

Откако ќе креирате сметка на `Github`, веднаш може да креирате и нов репозиториум. Основните работи што треба да се направат е да се внесе име на репозиторумот и, заради добра пракса, да се креира `Readme` датотеката. Потоа, во `Settngs` на репозиторумот поставете ги `gh-pages` во `docs`

_sliki tuka_


Потоа во `Rstudio` креирате нов проект преку `File -> New Project -> Version Control`, одбирате `Git` и ги пополнувате генералиите за репозиториумот: `URL`-то го копирате од Вашиот прелистувач и останатите вредности ги внесувате по желба. 

_sliki tuka_

Во следниот чекор `Rstudio` ќе побара да го внесете корисничкото име и лозинка за `Github` и ќе ја преземе содржината на репозиториумот. Ако сѐ оди како што треба, во панелот `Files` во `Rstudio` би требало да го видите `Readme`-то што го креиравте претходно.

Сега може да продолжите со работата, како што е опишано во претходните поглавја, за вчитување на податоци, анализа, пишување на `Rmarkdown`, итн. На крај откако ќе го креирате `HTML` документот од `Rmarkdown`, отворете го проектот преку прелистувачот на датотеки, креирајте папка `docs` и преместете го `HTML` документот преименувајќи го во `index.html`. 

Во панелот `Git` во `Rstudio` сега ќе Ви се појават новите датотеки со жолт прашалник покрај нивното име. Кликнете на `Staged` за да стане зелено, потоа на `Commit` и во ново отворениот прозорец внесете порака како на пр. `Mojot prv proekt na github`. Повторно кликнете на копчето `Commit` и потоа на зелената стрелка нагоре за `Push`. 

Штом процесот ќе заврши, вашиот изворен код и анализа со податоци ќе биде достапен на `github.com/korisnicko_ime/ime_na_repozitorum`, a Вашата веб страница на `korisnicko_ime.github.io/ime_na_repozitorium/`. Voila, објавивте сѐ одеднаш на интернет.


### Предности

Предностите на овој пристап се очигледни. Сѐ што работите се архивира со соодветни промени и истовремено е достапно за споделување во формат кој што совршено се вклопува на интернет. 

### Недостатоци

Недостатоците, или подобро речено, предизвиците, произлегуваат од потребата за совладување на `git`. Горниот пример во голема мера ги поедноставува работите и не се занимава со ниедно типично сценарио каде што правите промени или допувате код, итн. 

### Резиме