--- 
title: "Препораки за повторливо анализирање на податоци"
author: "Теофил Наков, Новица Наков, Слободен софтвер Македонија"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib, pckg.bib]
biblio-style: apalike
link-citations: yes
description: "Прирачник за повторливо анализирање и објавување на податоци. Дискутираме теми, процедури, и алатки од `R` екосистемот кои олеснуваат обработка на податоци со најдобрите и најбезбедни пракси и кои овозможуваат повторување на анализите со минимален труд од страна на надворешен корисник."
---

# Абстракт {-}

Волуменот на податоци достапни за најразлични потреби и од најразлични извори расте континуирано. Обработката и објавувето на резултати и податоци, дали од Интернет сообраќајот на вашиот вебсајт, од финансиските трансакции на вашата фирма, од анкети за политички мислења, или од лабораториски експерименти, станува се побрзо и полесно. Исто како и користењето на податоци собрани од Интернет за бизнис одлуки во рамките на вашата фирма. Заедничка за оваа транзиција кон наука за податоци, лична медицина, или бизнис интелегенција, е потребата за транспарентност, отвореност, и повторливост на анализите и резултатите од кои зависиме се повеќе и повеќе. Дали интерно, во нашата фирма за бизнис интелегенција, или јавно за нашите научни истражувања или епидемиолошки предвидувања, доверливи и безбедни процедури за анализа на податоци никогаш не биле толку значајни.

Во овој прирачник се осврнуваме токму на овие таканаречени „најдобри“ пракси за безбедно, стабилно, и _повторливо_ работење со податоци. Ќе зборуваме за проблемите што се јавуваат поради не-повторливост, за главните индикатори за не-повторливи проекти, како и за принципите и праксите кои ни овозможуваат да ги надминеме овие проблеми. Низ текстот се обидуваме да дадеме кратки примери, дали вербални или со код, кои ги илустрираат главните препораки и посочуваат кон адекватни софтверски решенија. Се држиме до програмскиот јазик `R`, којшто е од примарна значајност во светот на анализа на податоци и машинско учеке, има активна заедница посветена токму на проблемот на повторливи анализи, и голем број на алатки (библиотеки) кои го олеснуваат процесот на повторливост  при обработка на податоци. 

Нашата главна препорака е, без разлика на програмскиот јазик кој го користите, или стратегијата за организирање на проекти што најмногу прилега, бидете трпеливи, дисциплинирани, и доследни кон почитувањето на препораките за повторливост. Оваа инвестиција ќе ви се исплати на краток и долг рок во форма на заштедено време и ресурски, унапредување, или соработка.
